### ISSUE TITLE
分享的视频地址无法访问了！

### ISSUE THREAD

**Issue by yecaler** [threadshare/php#3]
分享的视频地址无法访问了！
大神请重新分享下！急需。感谢！

**Comment by supperyan** [comment]
所有的视频都无法访问！
前面发了你没看到，就多发了几个，不好意思。
![default](https://user-images.githubusercontent.com/25024969/48597972-88418c80-e99b-11e8-9349-06eac68f8b27.png)

**Comment by GiggleAll** [comment]
你要用哪个？  我找下发给你

**Comment by GiggleAll** [comment]
可能是被关掉了吧

**Comment by cheig** [comment]
你好，很多教程网盘链接都挂了，而且公众号关注了发送php开发没反应

**Comment by GiggleAll** [comment]
我刚看了一下是因为我把公众号配置了开发模式  那个应该不生效了
然后链接挂掉的话 最近没时间一个一个查到底是那个挂了 如果你最近要用的话 可以在这个issue中留言

**Comment by OldOrangeOne** [comment]
大佬 微信号多少

**Comment by Kun67000** [comment]
大佬，能不能在分享一下视频连接，很多都不能用了，万分感谢！

**Comment by threadshare** [comment]
需要那个  在issue里说吧  issue里提到的我会尽快更新上去
最近没时间逐一排查那些失效了

**Comment by XiaSean** [comment]
视频都不能用了

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by drskysu** [comment]
php基础巩固
PHP深入理解
这两个链接失效，能重新上传下吗？
