### ISSUE TITLE
如何安装php的intl扩展

### ISSUE THREAD

**Issue by sharkdeng** [threadshare/php#8]
你好！我想安装php的intl扩展，我用的是Mac Mojave系统内置的php。文件放在：
/usr/lib/php/extensions/
/usr/bin/php
我试过以下方法：
1）用brew install intl，没找到包，而且据说要再装个php版本。没成功
2）用sudo pecl install intl。找到包了，但make编译中缺少一个c文件头，编译失败。没成功。
3）用sudo port install php71-intl。成功安装了，但包放在它自己的文件夹里/opt/local/php71/extensions/intl.so。我想复制这个扩展到/usr/lib这个php文件夹里，提示没有权限，不能修改文件夹。
请问博主知道怎么解决这个问题吗？谢谢！！

**Comment by threadshare** [comment]
没有文件夹权限试一下sudo 
另外不知道是否安装成功了 可以参考看一下这个文章  http://note.rpsh.net/posts/2015/10/07/installing-php-intl-extension-os-x-el-capitan/
